### ISSUE TITLE
Lingering tasks from rails rewrite

### ISSUE THREAD

**Issue by maxjacobson** [maxjacobson/layabout#46]
# TODO
- [x] merge and "release" as 2.0
- [ ] delete bookmarks
- [ ] some kind of sync I guess? currently if you create a new folder, we won't see that until you next log in
- [ ] check if the old js contains anything worth returning
- [ ] indicated which links are videos visually
- [ ] ~~don't even try to embed non-videos in this PR~~
- [x] provide a way to click a link that takes you to the actual page
- [ ] switch to oauth2 for login to avoid people giving me their instapaper credentials directly. look at how IFTTT does Instapaper authentication and reverse engineer it I guess?
